Redesign filter sidebar
MITLibraries/timdex-ui pull request #112
Opened 2024-02-05 17:55 UTC by jazairi

#### Why these changes are being introduced:

The filter sidebar can become unwieldy, as all available filters are shown at all times.

#### Relevant ticket(s):

https://mitlibraries.atlassian.net/browse/GDT-127

#### How this addresses that need:

This restyles the filter sidebar as dropdown menus. In so doing, it also changes some behavior in the filter logic:

* Number of results is listed in the filter sidebar header.
* Applied filters are highlighted (previously, the 'applied' filter was added, but we hadn't done anything with it).
* Clicking an applied filter removes that filter (this replaces the previous removal mechanism, which removed all applied filters).

#### Side effects of this change:

* Some tests have been updated to reflect the new logic.
* The sidebar elements have an animation that's tied to height. I've set the height to 200px and added a scroll-behavior rule if the number of filters available exceeds that height. This is somewhat different from how the advanced search sidebar works, so I wanted to draw attention to it unless there are any concerns.
* The JS for the dropdown menus is so minimal that I included it in the view as a `script` tag, but I'm happy to load it via Sprockets if that's preferable.

#### Developer

- [x] All new ENV is documented in README
- [x] All new ENV has been added to Heroku Pipeline, Staging and Prod
- [x] ANDI or Wave has been run in accordance to
      [our guide](https://mitlibraries.github.io/guides/basics/a11y.html) and
      all issues introduced by these changes have been resolved or opened as new
      issues (link to those issues in the Pull Request details above)
- [ ] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer

- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

#### Requires database migrations?

NO

#### Includes new or updated dependencies?

NO

2024-02-05 20:54 UTC, JPrevost requested changes
If we can address the overlapping content before merge that would be great. If that proves hard to track down, I'd be okay with a ticket to loop back on it.

Otherwise this feels like what was requested to me and works with either mouse or keyboard navigation. 👍🏻

2024-02-05 20:54 UTC, JPrevost commented on app/views/search/_filter.html.erb
> +      <li class="term">
I'm not entirely sure why, but the scroll overlaps the content initially in Safari. If I select an element (via tab for example) it reflows the display and looks correct.


Expanded but with nothing selected the scrollbar overlaps the content
<img width="279" alt="Screenshot 2024-02-05 at 2 35 09 PM" src="https://github.com/MITLibraries/timdex-ui/assets/1386650/2ddedb44-72c2-4bc0-9762-db6bbabff8f6">

Tabbed into an element, the overlap is fixed
<img width="267" alt="Screenshot 2024-02-05 at 3 42 42 PM" src="https://github.com/MITLibraries/timdex-ui/assets/1386650/234e3885-2b31-43e6-9dea-08e2fd96b76a">

2024-02-05 20:54 UTC, JPrevost commented on app/views/search/results.html.erb
> +          <h3 class="hd-4"><em><%= @pagination[:hits] %> items</em></h3>
The hits value is a bit confusing for larger sets as displayed here.

Search for "organic chemistry" and it displays `10000 items`. It should probably display something something more like `10,000+ items`. I think we should expect TIMDEX API/OpenSearch to report "more than 10000 items" as "10000" and adjust the UI to anticipate that.

If you want to handle that in a separate ticket that is fine with me.

2024-02-06 22:01 UTC, jazairi commented
The latest commit addresses some initial feedback on this, both from this review and from Darcy (I shared it with her in a meeting yesterday afternoon). There are also a couple of things that came up while I was doing some testing related to the code review/QA feedback. More details in the commit message.

2024-02-08 18:16 UTC, JPrevost approved these changes

2024-02-08 20:14 UTC, merged